scrape_configs:
  - job_name: 'NmapCoreMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['nmap-core:8080']
        labels:
          application: 'NMAP Core Metrcs'